# Generated by Django 3.2.20 on 2023-09-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230902_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='join_date',
            new_name='joined_date',
        ),
    ]
